name: Daily IP Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"  # Runs three hours

jobs:
  update_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get the Proxy IPs
        run: python "scripts/getIPs.py"

      - name: Test the Proxy IPs
        run: python "scripts/cfSpeedTest.py"

      - name: Map the IPs with domains name
        run: python "scripts/mapDomain.py"

      - name: Update upstream DNS record
        run: python "scripts/cfRecUpdate.py"
        env: # Or as an environment variable
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
