name: Daily IP Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"  # Runs every day at midnight GMT+7

jobs:
  update_ip:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the script
        run: python "Quick Run-All.py"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} # API token still uses secrets
          CLOUDFLARE_ZONE_ID: ${{ env.CLOUDFLARE_ZONE_ID }} # Access env variables
          CLOUDFLARE_RECORD_NAME: ${{ env.CLOUDFLARE_RECORD_NAME }}
